###################### Server Makefile ##########################
# AUTHOR:   Samuel Terra Vieira                                 #
# ADDRESS:  Universidade Federal de Lavras                      #
# DATE:     23/09/2019                                          #
#################################################################

# The project name
PROJECT_NAME=server

include ../Makefile.mk