###################### Server Makefile ##########################
# AUTHOR:   Samuel Terra Vieira                                 #
# ADDRESS:  Universidade Federal de Lavras                      #
# DATE:     Out/2019                                          	#
#################################################################

# The project name
PROJECT_NAME=server

include ../Makefile.mk